###################################################################################
## HDL Shared FIFO CDC Constraints
##
## Auto-generated by gen_constraints.py
##
## Each constraint explicitly targets specific synchronizer flip-flops inside
## each CDC component instance.  If the design changes, only the known safe
## flip-flops are relaxed -- new logic will NOT be silently caught.
##
## Clock domains (effective periods from MacallanClocks.xml):
##   DmaClk  = 250 MHz  (3.7496000400 ns) -- ViClk / PCIe side
##   BusClk  =  80 MHz  (12.2487501250 ns) -- PllClk80 / comm side
##   Formula: 1/(freq*(1+PPM/1e6)) - jitter  [PPM=100, jitter=250ps]
##
## Writer FIFOs (TargetToHost): NiSharedFifoWriterCorex
## Reader FIFOs (HostToTarget): NiSharedFifoReaderCorex
##
###################################################################################

set hdl_dma_T 3.7496000400
set hdl_bus_T 12.2487501250

# =================================================================================
#  NiSharedFifoWriterCorex  (NiSharedFifoWriter / TargetToHost)
#    Push = DmaClk (250 MHz), Pop = PllClk80 (80 MHz)
# =================================================================================

# --- HandshakeBool: StreamStateBlock HandshakeStopStreamRequest (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*iPushToggle*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/BlkOut.oPushToggle0_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*oPushToggleToReady*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*iRdyPushToggle_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBool: StreamStateBlock HandshakeStopWithFlushRequest (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopWithFlushRequest/HandshakeBasex/*iPushToggle*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopWithFlushRequest/HandshakeBasex/BlkOut.oPushToggle0_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopWithFlushRequest/HandshakeBasex/*oPushToggleToReady*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopWithFlushRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopWithFlushRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStopWithFlushRequest/HandshakeBasex/*iRdyPushToggle_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBool: StreamStateBlock HandshakeStartStreamRequest (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*iPushToggle*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/BlkOut.oPushToggle0_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*oPushToggleToReady*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*iRdyPushToggle_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBool: StreamStateBlock HandshakeFlushTimeoutRequest (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeFlushTimeoutRequest/HandshakeBasex/*iPushToggle*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeFlushTimeoutRequest/HandshakeBasex/BlkOut.oPushToggle0_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeFlushTimeoutRequest/HandshakeBasex/*oPushToggleToReady*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeFlushTimeoutRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeFlushTimeoutRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeFlushTimeoutRequest/HandshakeBasex/*iRdyPushToggle_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBaseResetCross: StreamStateBlock StateToBusClk (hdl_dma_T -> hdl_bus_T) ---
# Handshake toggle/data/ready
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/*oPushToggle1x*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {2.0*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkIn.iStoredDatax*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.oDataFlopx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/*oPushToggleToReadyx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/*iRdyPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncIReset: c1(OClk)->c2(IClk), kSpeedUp=true  fwd=iT ret=oT
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncIReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay [expr {2.0*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncOReset: c1(IClk)->c2(OClk), kSpeedUp=false  fwd=oT ret=iT
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncOReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeStateToBusClkDomain/BlkOut.SyncOReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBaseResetCross: StreamStateBlock OverflowStop (hdl_dma_T -> hdl_bus_T) ---
# Handshake toggle/data/ready
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/*oPushToggle1x*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {2.0*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkIn.iStoredDatax*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.oDataFlopx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/*oPushToggleToReadyx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/*iRdyPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncIReset: c1(OClk)->c2(IClk), kSpeedUp=true  fwd=iT ret=oT
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncIReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay [expr {2.0*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncOReset: c1(IClk)->c2(OClk), kSpeedUp=false  fwd=oT ret=iT
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncOReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/StreamStateBlock.HandshakeOverflowStopRequest/BlkOut.SyncOReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBaseResetCross: BlkOverflow Overflow (hdl_dma_T -> hdl_bus_T) ---
# Handshake toggle/data/ready
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/*oPushToggle1x*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {2.0*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkIn.iStoredDatax*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.oDataFlopx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/*oPushToggleToReadyx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/*iRdyPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncIReset: c1(OClk)->c2(IClk), kSpeedUp=true  fwd=iT ret=oT
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncIReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay [expr {2.0*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncOReset: c1(IClk)->c2(OClk), kSpeedUp=false  fwd=oT ret=iT
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncOReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/BlkOverflow.HandshakeOverflow/BlkOut.SyncOReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]

# --- DmaPortInStrmFifo: gray counter DmaClk -> BusClk ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/iWriteSamplePtrUnsGray*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/SyncToOClk/GrayPtrClockCrossing.OutputGrayReg_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/SyncToOClk/GrayPtrClockCrossing.OutputGrayReg_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/SyncToOClk/GrayPtrClockCrossing.OutputGrayReg/*} -filter {IS_SEQUENTIAL==true}]

# --- DmaPortInStrmFifo: disable signal BusClk -> DmaClk ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/iWritesDisabledSampPtrUnsGray*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/SyncToOClk/DisableSignalClockCrossing.SyncToOClk_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/SyncToOClk/DisableSignalClockCrossing.SyncToOClk_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/SyncToOClk/DisableSignalClockCrossing.SyncToOClk*} -filter {IS_SEQUENTIAL==true}]

# --- DmaPortFifoPtrClockCrossing: read ptr BusClk -> DmaClk (hdl_bus_T -> hdl_dma_T) ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/iTogglePush*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/oPushRcvd_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/oPushRcvd_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/oPushRcvd_reg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {2.0*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/iDataToPush*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/DataReg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/oAck*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/iAckRcvd_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/iAckRcvd_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/OClkToIClkCrossing.SyncToIClk/iAckRcvd_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBaseResetCross: WritePointerHandshake (hdl_dma_T -> hdl_bus_T) ---
# Handshake toggle/data/ready
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/*oPushToggle1x*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {2.0*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkIn.iStoredDatax*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.oDataFlopx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/*oPushToggleToReadyx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/*iRdyPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncIReset: c1(OClk)->c2(IClk), kSpeedUp=true  fwd=iT ret=oT
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncIReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay [expr {2.0*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncOReset: c1(IClk)->c2(OClk), kSpeedUp=false  fwd=oT ret=iT
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncOReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortInStrmFifox/DmaPortInStrmFifoFlagsx/WritePointerHandshake/BlkOut.SyncOReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]

# --- DoubleSyncBool: FifoClear ToPush (hdl_bus_T -> hdl_dma_T) ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/PushSynchNeeded.ToPushDblSync*iDlySigx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/PushSynchNeeded.ToPushDblSync*DoubleSyncAsyncInBasex/oSig_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/PushSynchNeeded.ToPushDblSync*DoubleSyncAsyncInBasex/oSig_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/PushSynchNeeded.ToPushDblSync*DoubleSyncAsyncInBasex/oSigx*} -filter {IS_SEQUENTIAL==true}]

# --- DoubleSyncBool: FifoClear FromPush (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/PushSynchNeeded.FromPushDblSync*iDlySigx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/PushSynchNeeded.FromPushDblSync*DoubleSyncAsyncInBasex/oSig_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/PushSynchNeeded.FromPushDblSync*DoubleSyncAsyncInBasex/oSig_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/PushSynchNeeded.FromPushDblSync*DoubleSyncAsyncInBasex/oSigx*} -filter {IS_SEQUENTIAL==true}]

# --- PulseSyncBase: ClearToPush (hdl_bus_T -> hdl_dma_T) ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/PulseSyncBasex/iHoldSigInx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/PulseSyncBasex/iSigOutx*} -filter {IS_SEQUENTIAL==true}]

# --- ClearToPush: oRegisteredSigAck -> PulseSync iSigOut_ms ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/oRegisteredSigAck*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPush/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}]

# --- PulseSyncBase: PopToPush (hdl_bus_T -> hdl_dma_T) ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/iHoldSigInx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/iSigOutx*} -filter {IS_SEQUENTIAL==true}]

# --- PulseSyncBase: PushToPop (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/iHoldSigInx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoWriterCorex/DmaPortCommIfcComponentEnableChainx/Input.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/iSigOutx*} -filter {IS_SEQUENTIAL==true}]

# --- Async reset paths: NiSharedFifoWriterCorex CLR/PRE ---
set_false_path -to [get_pins -quiet -hier -filter {NAME =~ *NiSharedFifoWriterCorex/*/CLR && IS_LEAF}]
set_false_path -to [get_pins -quiet -hier -filter {NAME =~ *NiSharedFifoWriterCorex/*/PRE && IS_LEAF}]

# =================================================================================
#  NiSharedFifoReaderCorex  (NiSharedFifoReader / HostToTarget)
#    Push = PllClk80 (80 MHz), Pop = DmaClk (250 MHz)
# =================================================================================

# --- HandshakeBool: StreamStateBlock HandshakeStopStreamRequest (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*iPushToggle*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/BlkOut.oPushToggle0_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*oPushToggleToReady*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStopStreamRequest/HandshakeBasex/*iRdyPushToggle_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBool: StreamStateBlock HandshakeStartStreamRequest (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*iPushToggle*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/BlkOut.oPushToggle0_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*oPushToggleToReady*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*iRdyPushToggle_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeStartStreamRequest/HandshakeBasex/*iRdyPushToggle_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBaseResetCross: StreamStateBlock UnderflowStop (hdl_dma_T -> hdl_bus_T) ---
# Handshake toggle/data/ready
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/*oPushToggle1x*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {2.0*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkIn.iStoredDatax*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.oDataFlopx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/*oPushToggleToReadyx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/*iRdyPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncIReset: c1(OClk)->c2(IClk), kSpeedUp=true  fwd=iT ret=oT
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncIReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay [expr {2.0*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncOReset: c1(IClk)->c2(OClk), kSpeedUp=false  fwd=oT ret=iT
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncOReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/StreamStateBlock.HandshakeUnderflowStopRequest/BlkOut.SyncOReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBaseResetCross: BlkUnderflow Underflow (hdl_dma_T -> hdl_bus_T) ---
# Handshake toggle/data/ready
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/*oPushToggle1x*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {2.0*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkIn.iStoredDatax*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.oDataFlopx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/*oPushToggleToReadyx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/*iRdyPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncIReset: c1(OClk)->c2(IClk), kSpeedUp=true  fwd=iT ret=oT
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncIReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay [expr {2.0*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncOReset: c1(IClk)->c2(OClk), kSpeedUp=false  fwd=oT ret=iT
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncOReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/BlkUnderflow.HandshakeUnderflow/BlkOut.SyncOReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]

# --- HandshakeBaseResetCross: HandshakeFullCount (hdl_dma_T -> hdl_bus_T) ---
# Handshake toggle/data/ready
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.oPushToggle0_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/*oPushToggle1x*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {2.0*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkIn.iStoredDatax*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.oDataFlopx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/*oPushToggleToReadyx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/*iRdyPushToggle_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/*iRdyPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncIReset: c1(OClk)->c2(IClk), kSpeedUp=true  fwd=iT ret=oT
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncIReset/c2ResetFe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncIReset/SpeedUpWithFeFlopGen.SyncToClk2REfromFE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncIReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncIReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay [expr {2.0*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncIReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkIn.iPushTogglex*} -filter {IS_SEQUENTIAL==true}]
# SyncOReset: c1(IClk)->c2(OClk), kSpeedUp=false  fwd=oT ret=iT
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncOReset/c1ResetFastLclx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncOReset/c2ResetRe_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncOReset/DontSpeedUpWithFeFlopGen.SyncToClk2REfromRE*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncOReset/c1ResetFromClk2_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/HandshakeFullCount/BlkOut.SyncOReset/c1ResetFromClk2_reg*} -filter {IS_SEQUENTIAL==true}]

# --- DmaPortOutStrmFifo: gray counter DmaClk -> BusClk ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/oReadSamplePtrUnsGray*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/iReadSamplePtrUnsGray_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/iReadSamplePtrUnsGray_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/iReadSamplePtrUnsGray_reg*} -filter {IS_SEQUENTIAL==true}]

# --- DmaPortFifoPtrClockCrossing: write ptr BusClk -> DmaClk (hdl_bus_T -> hdl_dma_T) ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/iTogglePush*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/oPushRcvd_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/oPushRcvd_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/oPushRcvd_reg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {2.0*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/iDataToPush*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/DataReg*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/oAck*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/iAckRcvd_ms*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/iAckRcvd_ms*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/iAckRcvd_reg*} -filter {IS_SEQUENTIAL==true}]

# --- PCC DataReg -> bStateInDefaultClkDomainClean: PllClk80 -> DmaClk ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortOutStrmFifox/DmaPortOutStrmFifoFlagsx/IClkToOClkCrossing.SyncToOClk/DataReg*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/bStateInDefaultClkDomainClean_reg*} -filter {IS_SEQUENTIAL==true}]

# --- DoubleSyncBool: FifoClear ToPop (hdl_bus_T -> hdl_dma_T) ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/PopSynchNeeded.ToPopDblSync*iDlySigx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/PopSynchNeeded.ToPopDblSync*DoubleSyncAsyncInBasex/oSig_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/PopSynchNeeded.ToPopDblSync*DoubleSyncAsyncInBasex/oSig_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/PopSynchNeeded.ToPopDblSync*DoubleSyncAsyncInBasex/oSigx*} -filter {IS_SEQUENTIAL==true}]

# --- DoubleSyncBool: FifoClear FromPop (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/PopSynchNeeded.FromPopDblSync*iDlySigx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/PopSynchNeeded.FromPopDblSync*DoubleSyncAsyncInBasex/oSig_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/PopSynchNeeded.FromPopDblSync*DoubleSyncAsyncInBasex/oSig_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/PopSynchNeeded.FromPopDblSync*DoubleSyncAsyncInBasex/oSigx*} -filter {IS_SEQUENTIAL==true}]

# --- PulseSyncBase: ClearToPop (hdl_bus_T -> hdl_dma_T) ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/PulseSyncBasex/iHoldSigInx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/PulseSyncBasex/iSigOutx*} -filter {IS_SEQUENTIAL==true}]

# --- ClearToPop: oRegisteredSigAck -> PulseSync iSigOut_ms ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/oRegisteredSigAck*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.ClearToPop/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}]

# --- PulseSyncBase: PopToPush (hdl_dma_T -> hdl_bus_T) ---
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/iHoldSigInx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PopToPush/PulseSyncBasex/iSigOutx*} -filter {IS_SEQUENTIAL==true}]

# --- PulseSyncBase: PushToPop (hdl_bus_T -> hdl_dma_T) ---
set_max_delay -datapath_only $hdl_dma_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/iHoldSigInx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_dma_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/oHoldSigIn_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only $hdl_bus_T \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/oLocalSigOutCEx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}]
set_max_delay -datapath_only [expr {0.5*$hdl_bus_T}] \
  -from [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/iSigOut_msx*} -filter {IS_SEQUENTIAL==true}] \
  -to   [get_cells -quiet {*NiSharedFifoReaderCorex/DmaPortCommIfcComponentEnableChainx/Output.FifoClearController/NiFpgaFifoPortResetx/Crossing.PushToPop/PulseSyncBasex/iSigOutx*} -filter {IS_SEQUENTIAL==true}]

# --- Async reset paths: NiSharedFifoReaderCorex CLR/PRE ---
set_false_path -to [get_pins -quiet -hier -filter {NAME =~ *NiSharedFifoReaderCorex/*/CLR && IS_LEAF}]
set_false_path -to [get_pins -quiet -hier -filter {NAME =~ *NiSharedFifoReaderCorex/*/PRE && IS_LEAF}]
