# ModelSim load script for tb_all
# Generated by nihdl create-modelsim

# Open the project
if { ! [info exists niSimInitialized] } {
  set niSimInitialized 1
}

# Load the design
vsim -t 1ps -voptargs=+acc tb_all

# Add all signals to waveform
add wave -r /*

# Run the simulation
# Uncomment below to auto-run:
# run -all
