# ModelSim batch simulation script for tb_all
# Generated by nihdl create-modelsim

# Load the design
vsim -t 1ps tb_all

# Run simulation
onbreak {resume}
run -all

# Report results
if { [find signals -r /*/aSimComplete] ne "" } {
    echo "Simulation complete signal found"
}

quit -f
