# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/dev/github8/hdl-shared/host_interfaces/fifo/VivadoProject/HdlFifo.runs/synth_1/tb_HdlSharedHostFifo.vhd.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/dev/github8/hdl-shared/host_interfaces/fifo/VivadoProject/HdlFifo.cache/wt [current_project]
set_property parent.project_path C:/dev/github8/hdl-shared/host_interfaces/fifo/VivadoProject/HdlFifo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/dev/github8/hdl-shared/host_interfaces/fifo/VivadoProject/HdlFifo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_CommonCores.1.0.0a26/CommonFiles/Packages/PkgNiUtilities.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/DFlopBase/Xilinx/DFlop.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/DFlop/DFlopBool.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/DFlopBase/Xilinx/DFlopFallingEdge.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/DFlop/DFlopBoolFallingEdge.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_CommonCores.1.0.0a26/CommonFiles/Packages/PkgGray.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/DFlop/DFlopGray.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/DFlop/DFlopSlvResetVal.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/DFlop/DFlopUnsigned.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_nidmaip.1.1.0d14/PCIe/CommonFiles/Source/PkgCommunicationInterface.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/common/rtl-lvfpga/lvgen/PkgCommIntConfiguration.vhd
  C:/dev/github8/hdl-shared/host_interfaces/fifo/objects/gatheredfiles/PkgNiDmaConfig.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_CommonCores.1.0.0a26/CommonFiles/Packages/PkgNiSimType.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_CommonCores.1.0.0a26/CommonFiles/Packages/PkgNiString.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_CommonCores.1.0.0a26/CommonFiles/Packages/PkgScoreboard.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_CommonCores.1.0.0a26/CommonFiles/Packages/PkgNiSim.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_CommonCores.1.0.0a26/CommonFiles/Packages/PkgXReg.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_nidmaip.1.1.0d14/CommonFiles/Source/DMAC/PkgBaggageRegTypeRegMap.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_nidmaip.1.1.0d14/CommonFiles/Source/DMAC/PkgNiDmaRegMap.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_nidmaip.1.1.0d14/CommonFiles/Source/DMAC/PkgNiDma.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_fb9f3ca7a3/CommInterfaces/DmaPort/MasterPort/PkgDmaPortCommIfcMasterPort.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_b0d75c529f/CommInterfaces/DmaPort/CommonFiles/PkgDmaPortCommunicationInterface.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/distribution/release/fpgaDigitalDesigns/LabVIEW/rvi/Vivado/HDL/Timing/source/TimeoutManager.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/ClockCrossing/DoubleSync/DoubleSyncAsyncInBase.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/ClockCrossing/DoubleSync/DoubleSyncBase.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/ClockCrossing/DoubleSync/DoubleSyncBool.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/ClockCrossing/PulseSync/PulseSyncBase.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/ClockCrossing/PulseSync/PulseSyncBool.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_f7a2160f0a/NiFpgaCores/ClockCrossing/PulseSync/NiFpgaPulseSyncBaseWrapper.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_54399e566f/source/NiFpgaFifoPortReset/Source/NiFpgaFifoPortReset.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_5b65d0e8ad/source/NiFpgaFifoClearControl/Source/NiFpgaFifoClearControl.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_5b96c0056b/DmaPort/Dma/DmaFifo/DmaPortCommIfcComponentEnableChain.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_7fae59b6b5/DmaPort/Dma/Common/PkgDmaPortCommIfcStreamStates.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_1eed6bb841/DmaPort/Dma/DmaFifo/DmaPortCommIfcComponentInputStateHolder.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_e45f61ea54/DmaPort/Dma/DmaFifo/DmaPortCommIfcComponentOutputStateHolder.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/ClockCrossing/Handshake/ResetSync.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/ClockCrossing/Handshake/HandshakeBaseResetCross.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_0f2d09f163/DmaPort/Dma/DmaFifo/DmaPortCommIfcComponentStateTransitionEnableChain.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_1e01a464f5/DmaPort/Dma/DmaFifo/DmaPortCommIfcComponentStreamStateEnableChain.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_165982fc9e/NiFpgaCores/Xilinx/RAM/NiFpgaSimpleDualPortRAM_ByteEnable.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_3d99bdc97b/DmaPort/Dma/DmaFifo/DmaPortCommIfcSimpleDualPortRAM_ByteEnable.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_8bfb4cd1ff/DmaPort/Dma/DmaFifo/DmaPortFifoPtrClockCrossing.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_68d7164f19/DmaPort/Dma/DmaFifo/DmaPortFifoSyncGrayCounters.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_9b2386965a/DmaPort/Dma/DmaFifo/PkgDmaPortDataPackingFifo.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_265da687ac/Dma/DmaFifo/InputDataPackFifo/DmaPortInStrmDPRAM.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_05f1d0cc85/Dma/DmaFifo/InputDataPackFifo/DmaPortInStrmFifoFlags.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_1d73c6a7a5/Dma/DmaFifo/InputDataPackFifo/DmaPortInStrmFifo.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_CommonCores.1.0.0a26/CommonFiles/Packages/PkgOneHot.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/nicores_CommonCores.1.0.0a26/CommonFiles/Packages/PkgByteArray.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_6e2a26a045/Dma/DmaFifo/OutputDataPackFifo/DmaPortOutStrmDPRAM.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_051d445cab/Dma/DmaFifo/OutputDataPackFifo/DmaPortOutStrmFifoFlags.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_5a1c34a822/Dma/DmaFifo/OutputDataPackFifo/DmaPortOutStrmFifo.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/ClockCrossing/Handshake/HandshakeBase.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/source/rvi/Vivado/HDL/CommonFiles/NiCores/ClockCrossing/Handshake/HandshakeSLV.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_381e204dc2/DmaPort/Dma/DmaFifo/PkgDmaPortDmaFifos.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_60a4178d66/source/NiFpgaFifoCountControl/source/NiFpgaFifoCountControl.vhd
  C:/dev/github8/hdl-shared/host_interfaces/fifo/HDL/HdlSharedInputFifoInterface.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_bba02d3110/source/PkgNiFpgaFifo/Source/PkgNiFpgaFifo.vhd
  C:/dev/github8/hdl-shared/host_interfaces/fifo/objects/gatheredfiles/PkgFpgaDeviceSpecs.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_33a567e4dd/source/NiFpgaFlipFlopFifo/Source/NiFpgaFlipFlopFifo.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_bd99ce4e52/source/NiFpgaFifoPopBuffer/Source/LutRamFifoFlags.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_39804f5515/source/NiFpgaFifoPopBuffer/Source/NiFpgaLowLatencyLutRam.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_2f5f983460/source/NiFpgaFifoPopBuffer/Source/NiFpgaLutRamFifo.vhd
  C:/dev/github8/hdl-shared/deps/flexrio-deps/encrypted/fpgaDigitalDesigns.25.1.0f405/_h_7806320814/source/NiFpgaFifoPopBuffer/Source/NiFpgaFifoPopBuffer.vhd
  C:/dev/github8/hdl-shared/host_interfaces/fifo/HDL/HdlSharedOutputFifoInterface.vhd
  C:/dev/github8/hdl-shared/host_interfaces/fifo/HDL/tb_HdlSharedHostFifo.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top tb_HdlSharedHostFifo.vhd -part xcku040-ffva1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tb_HdlSharedHostFifo.vhd.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tb_HdlSharedHostFifo.vhd_utilization_synth.rpt -pb tb_HdlSharedHostFifo.vhd_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
