# This file contains settings for the HDL Shared Host Register project. The purpose of this is to generate a Vivado 
# project that can be used to run testbenches on the register code.  The aspects of this project settings that are 
# related to generating a FPGA bitfile or a LabVIEW FPGA target are ignored.

[GeneralSettings]
TargetFamily = 
BaseTarget = 
LabVIEWPath = 


[VivadoProjectSettings]
TopLevelEntity = tb_NiSharedHostRegister
FPGAPart = xcku040-ffva1156-2-e
# note: no spaces allowed in project name, do not include .xpr extension
VivadoProjectName = HdlRegister
VivadoToolsPath = C:/NIFPGA/programs/Vivado2021_1
VivadoProjectFilesLists =
    vivadoprojectsources.txt
    vivadoprojectdeps.txt
VivadoProjectVHDL2008FilesLists =
ConstraintsTemplates =
CustomConstraintsFile =
VivadoProjectConstraintsFiles =
VivadoTclScriptsFolder = ../common/TCL
UseGeneratedLVWindowFiles = False
TheWindowFolder = 
CodeGenerationResultsStub = 


[LVFPGATargetSettings]
# Inputs
LVTargetBoardIO = 
IncludeCLIPSocket = 
IncludeLVTargetBoardIO = 
LVTargetName = 
LVTargetGUID = 
LVTargetInstallFolder = 
LVTargetConstraintsFiles =
LVTargetMenusFolder = 
LVTargetInfoIni = 
LVTargetExcludeFiles = 
NumHdlRegisters = 

# Templates
WindowVhdlTemplates = 
TargetXMLTemplates =

# Outputs
WindowVhdlOutputFolder = 
BoardIOSignalAssignmentsExample = 
LVTargetPluginFolder = 
BoardIOXML = 
ClockXML = 


[CLIPMigrationSettings]
# Inputs
CLIPXML =
CLIPHDLTop =
CLIPXDCIn =
CLIPInstancePath =

# Outputs
LVTargetBoardIO = 
CLIPInstantiationExample = 
CLIPtoWindowSignalDefinitions = 
CLIPXDCOutFolder = 


[LVWindowNetlistSettings]
# Inputs
VivadoProjectExportXPR =

# Outputs
TheWindowFolder = 