# This file contains settings for the HDL Shared Host Register project. The purpose of this is to generate a Vivado 
# project that can be used to run testbenches on the register code.  The aspects of this project settings that are 
# related to generating a FPGA bitfile or a LabVIEW FPGA target are ignored.

[GeneralSettings]
TargetFamily = 
BaseTarget = 
LabVIEWPath = 


[VivadoProjectSettings]
TopLevelEntity = tb_all
FPGAPart = xcku040-ffva1156-2-e
# note: no spaces allowed in project name, do not include .xpr extension
VivadoProjectName = HdlInputFifo
VivadoToolsPath = C:/NIFPGA/programs/Vivado2021_1
VivadoProjectFilesLists =
    vivadoprojectsources.txt
    vivadoprojecttestbenchsources.txt    
    vivadoprojectdepsdev.txt
VivadoProjectVHDL2008FilesLists =
    vivadoprojectvhdl2008files.txt
ConstraintsTemplates =
CustomConstraintsFile =
VivadoProjectConstraintsFiles =
VivadoTclScriptsFolder = ../common/TCL
UseGeneratedLVWindowFiles = False
TheWindowFolder = 
CodeGenerationResultsStub = 


[LVFPGATargetSettings]
# Inputs
LVTargetBoardIO = 
IncludeCLIPSocket = 
IncludeLVTargetBoardIO = 
LVTargetName = 
LVTargetGUID = 
LVTargetInstallFolder = 
LVTargetConstraintsFiles =
LVTargetMenusFolder = 
LVTargetInfoIni = 
LVTargetExcludeFiles = 
NumHdlRegisters = 

# Templates
WindowVhdlTemplates = 
TargetXMLTemplates =

# Outputs
WindowVhdlOutputFolder = 
BoardIOSignalAssignmentsExample = 
LVTargetPluginFolder = 
BoardIOXML = 
ClockXML = 


[ModelSimSettings]
ModelSimToolsPath = C:/modeltech_pe_2020.4
XilinxSimLibPath = C:/dev/libraries/vivado/2021.1/modelsim_PE_2020


[CLIPMigrationSettings]
# Inputs
CLIPXML =
CLIPHDLTop =
CLIPXDCIn =
CLIPInstancePath =

# Outputs
LVTargetBoardIO = 
CLIPInstantiationExample = 
CLIPtoWindowSignalDefinitions = 
CLIPXDCOutFolder = 


[LVWindowNetlistSettings]
# Inputs
VivadoProjectExportXPR =

# Outputs
TheWindowFolder = 