
# Auto-generated by nihdl check-syntax
open_project {PROJECT_FILE_NAME}
update_compile_order -fileset sources_1
set_property top TOP_ENTITY_NAME [current_fileset]


if {[catch {
    synth_design -rtl -top TOP_ENTITY_NAME -part FPGA_PART_NAME -name nihdl_check_syntax
} result options]} {
    puts stderr $result
    if {[dict exists $options -errorinfo]} {
        puts stderr [dict get $options -errorinfo]
    }
    puts "NIHDL_CHECK_SYNTAX=FAILED"
    exit 1
}

puts "NIHDL_CHECK_SYNTAX=PASSED"
exit 0
